clc; clear all; close all;
load('salmon.mat');
%plot(t, salmon, 'ro');
%hold on;
linCoeff = polyfit(t, salmon, 1);
m = linCoeff(1);
b = linCoeff(2);
save('A1.dat', 'm', '-ascii');
pop2018 = m*80 + b;
save('A2.dat', 'pop2018', '-ascii');
sal_pred = m*t + b;
E_lin = sqrt(sum((sal_pred - salmon).^2) / length(salmon));
save('A3.dat', 'E_lin', '-ascii');
polyCoeff_2 = polyfit(t, salmon, 2);
sal_deg2 = polyval(polyCoeff_2, 80);
save('A4.dat', 'sal_deg2', '-ascii');
polyCoeff_5 = polyfit(t, salmon, 5);
sal_deg5 = polyval(polyCoeff_5, 80);
save('A5.dat', 'sal_deg5', '-ascii');
polyCoeff_20 = polyfit(t, salmon, 20);
sal_deg20 = polyval(polyCoeff_20, 80);
save('A6.dat', 'sal_deg20', '-ascii');
z = log(salmon);
expCoeff = polyfit(t, z, 1);
expRate = expCoeff(1);
expInit = exp(expCoeff(2));
realExpCoeff = [expInit expRate];
save('A7.dat', 'realExpCoeff', '-ascii');
sal_exp = expInit*exp(expRate*80);
save('A8.dat', 'sal_exp', '-ascii');
wrap = @(v)(rms_er(v(1), v(2), v(3)));
minCoeff = fminsearch(wrap, [0.001; -0.01; 10]);
sal_fmin = exp(minCoeff(1)*80^2 + minCoeff(2)*80 + minCoeff(3)); 
save('A9.dat', 'sal_fmin', '-ascii');
sal_spline = spline(t, salmon, 80);
save('A10.dat', 'sal_spline', '-ascii');
